package Banking;


/**
* Banking/Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Monday, 18 May 2026 23:58:51 o'clock IST
*/

public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
