package Banking;


/**
* Banking/AccountPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Monday, 18 May 2026 23:58:51 o'clock IST
*/

public abstract class AccountPOA extends org.omg.PortableServer.Servant
 implements Banking.AccountOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getBankName", new java.lang.Integer (0));
    _methods.put ("deposit", new java.lang.Integer (1));
    _methods.put ("withdraw", new java.lang.Integer (2));
    _methods.put ("getBalance", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Banking/Account/getBankName
       {
         String accountNo = in.read_string ();
         String $result = null;
         $result = this.getBankName (accountNo);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Banking/Account/deposit
       {
         String accountNo = in.read_string ();
         double amount = in.read_double ();
         this.deposit (accountNo, amount);
         out = $rh.createReply();
         break;
       }

       case 2:  // Banking/Account/withdraw
       {
         try {
           String accountNo = in.read_string ();
           double amount = in.read_double ();
           this.withdraw (accountNo, amount);
           out = $rh.createReply();
         } catch (Banking.InsufficientBalance $ex) {
           out = $rh.createExceptionReply ();
           Banking.InsufficientBalanceHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // Banking/Account/getBalance
       {
         String accountNo = in.read_string ();
         double $result = (double)0;
         $result = this.getBalance (accountNo);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Banking/Account:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Account _this() 
  {
    return AccountHelper.narrow(
    super._this_object());
  }

  public Account _this(org.omg.CORBA.ORB orb) 
  {
    return AccountHelper.narrow(
    super._this_object(orb));
  }


} // class AccountPOA
