package Banking;

/**
* Banking/AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Monday, 18 May 2026 23:58:51 o'clock IST
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public Banking.Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (Banking.Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Banking.AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Banking.AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Banking.AccountHelper.type ();
  }

}
