package Banking;


/**
* Banking/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Monday, 18 May 2026 23:58:51 o'clock IST
*/

public interface AccountOperations 
{
  String getBankName (String accountNo);
  void deposit (String accountNo, double amount);
  void withdraw (String accountNo, double amount) throws Banking.InsufficientBalance;
  double getBalance (String accountNo);
} // interface AccountOperations
