package Banking;


/**
* Banking/InsufficientBalance.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Monday, 18 May 2026 23:58:51 o'clock IST
*/

public final class InsufficientBalance extends org.omg.CORBA.UserException
{
  public String message = null;

  public InsufficientBalance ()
  {
    super(InsufficientBalanceHelper.id());
  } // ctor

  public InsufficientBalance (String _message)
  {
    super(InsufficientBalanceHelper.id());
    message = _message;
  } // ctor


  public InsufficientBalance (String $reason, String _message)
  {
    super(InsufficientBalanceHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class InsufficientBalance
