package Banking;

/**
* Banking/InsufficientBalanceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banking.idl
* Monday, 18 May 2026 23:58:51 o'clock IST
*/

public final class InsufficientBalanceHolder implements org.omg.CORBA.portable.Streamable
{
  public Banking.InsufficientBalance value = null;

  public InsufficientBalanceHolder ()
  {
  }

  public InsufficientBalanceHolder (Banking.InsufficientBalance initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Banking.InsufficientBalanceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Banking.InsufficientBalanceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Banking.InsufficientBalanceHelper.type ();
  }

}
