module Banking{

    exception InsufficientBalance{
            string message;
    };

    interface Account{
        string getBankName(in string accountNo);
        void deposit(in string accountNo, in double amount);
        void withdraw(in string accountNo, in double amount) raises (InsufficientBalance);
        double getBalance( in string accountNo);
    };

};